name: Push Unity Updates

on:
  push:
    branches:
      - main

jobs:
  push-updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Push updates to private repository
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/sourav1570/YOUR_REPO.git
          git push origin main
